### ISSUE TITLE
Allow specifying values + priorities in one step

### ISSUE THREAD

**Issue by ndsvw** [ndsvw/Fluent-Random-Picker#11]
(Based on [issue 10 - 3rd comment](https://github.com/ndsvw/Fluent-Random-Picker/issues/10#issuecomment-1117221577) and [issue 10 - 4th comment](https://github.com/ndsvw/Fluent-Random-Picker/issues/10#issuecomment-1118256284) by [phillip-haydon](https://github.com/phillip-haydon))

Idea: Something like this:

```c#
var options = Out.Of().WeightedValues(lootable.Select(x => new WeightedValue(x, x.Weight));

var drop = options.PickOne();
```

Advantage:

- No mistakes with order (order of values and percentages/weights) need to match when using `Out.Of().Values(...).AndWeights(...)` syntax
- Easy way if the values and percentages/weights are already combined in an object.

**Comment by ndsvw** [comment]
## Possibility 1:

```c#
var elements = new List<MyValuePriorityPair>();
Out.Of().PrioritizedElements(elements)
    .WithValueSelector(x => x.Value)
    .AndPercentageSelector(x => x.Percentage)
    .PickOne();
Out.Of().PrioritizedElements(elements)
    .WithValueSelector(x => x.Value)
    .AndWeightSelector(x => x.Weight)
    .PickOne();
```

- (+) Good readability
- (+) More fluency (it's a fluency project)
- (+) Performance: optimal
- (+-) Difficulty: intermediate

## Possibility 2:

```c#
var elements2 = new List<(string Value, int Priority)>();
Out.Of().WeightedValues(elements2)
    .PickOne();
Out.Of().PercentageValues(elements2)
    .PickOne();
```

- (+) Good readability
- (-) Makes the API harder to use (Out.Of().<Value,Values,WeightedValues,PercentageValues>)
- (+) Performance: optimal
- (+) Difficulty: very easy

## Possibility 3:

```c#
var elements3 = new List<X>();
Out.Of().WeightedValues(elements3.Select(x => new WeightedValue(x.Value, x.Weight)))
    .PickOne();
Out.Of().PercentageValues(elements3.Select(x => new PercentageValue(x.Value, x.Percentage)))
    .PickOne();
```

- (-) Not good readability
- (-) Makes the API harder to use (Out.Of().<Value,Values,WeightedValues,PercentageValues>)
- (+-) Performance: Maybe redundant instantiations
- (+) WeightedValue/PercentageValue could possibly be used internally, too (see ValuePriorityPair
- (-) Difficulty: more difficult (one had to know that the types WeightedValue/PercentageValue exist)

**Comment by phillip-haydon** [comment]
I think I prefer approach 1.

**Comment by ndsvw** [comment]
### What's possible at the moment:

```c#
var vals = new List<IWeightedValues>();
var x = Out.Of().Values(vals).WithWeights(vals.Select(x => x.Weight)).PickOne();
```

`x` is a whole `IWeightedValue`.

### With the new feature of this issue, this could be possible:

```c#
var elements = new List<IWeightedValue>();
var x = Out.Of().PrioritizedElements(elements)
    .WithValueSelector(x => x)
    .AndWeightSelector(x => x.Weight)
    .PickOne();
```

Maybe, the WithValueSelector should be optional, so that it's not required to write `x => x` if you want to return the whole element:
```c#
var elements = new List<IWeightedValue>();
var x = Out.Of().PrioritizedElements(elements)
    .WeightSelector(x => x.Weight)
    .PickOne();
```

`x` is a whole `IWeightedValue` again.

**Comment by ndsvw** [comment]
New feature is available. It works with version 3.3.0.

Example:

```c#
class Item {
    public int Rarity { get; set; }
    public string Name { get; set; }
}

var items = new Item[]
{
    new Item { Name = "Stone", Rarity = 5 }, // common
    new Item { Name = "Silver helmet", Rarity = 2 }, // uncommon
    new Item { Name = "Gold sword", Rarity = 1 }, // rare
};

var itemName = Out.Of()
                  .PrioritizedElements(items)
                  .WithValueSelector(x => x.Name)
                  .AndWeightSelector(x => x.Rarity)
                  .PickOne();

// itemName is "Stone" in 5/8 of the cases, "Silver helmet" in 2/8 of the cases and "Gold sword" in 1/8 of the cases.
// If no value selector is specified, the whole item object will be returned instead of only its name.
```
