### ISSUE TITLE
NotEnoughValuesToPickException when only one value is passed

### ISSUE THREAD

**Issue by SapiensAnatis** [ndsvw/Fluent-Random-Picker#49]
Having another issue with my drops code :pensive: 

If my enemy list (which is data driven) happens to only contain one element, it throws `NotEnoughValuesToPickException` when initializing the picker.

I am initializing an `IPick<DropEntity>` as follows
```csharp
IPick<AtgenEnemy> randomBuilder = Out.Of()
    .PrioritizedElements(enemyList)
    .WithWeightSelector(x =>x.Weight);
```                

and the stack trace is 

```
FluentRandomPicker.Exceptions.NotEnoughValuesToPickException: Exception of type 'FluentRandomPicker.Exceptions.NotEnoughValuesToPickException' was thrown.
   at FluentRandomPicker.SelectorBasedRandomPicker`1.PrioritizedElements(IEnumerable`1 elements)
   at FluentRandomPicker.NonGenericOf.PrioritizedElements[T](IEnumerable`1 ts)
   at DragaliaAPI.Features.Dungeon.QuestEnemyService.GetEnemyPicker(AtgenEnemy[] enemyList)
```

It would be helpful for me if this was fixed, but I can see why it would be intended. I recognize that initializing a random picker with one element is a bit weird, but there's nothing technically stopping it from always returning the same value. Let me know your thoughts :slightly_smiling_face:

**Comment by ndsvw** [comment]
Hello, it was implemented like this for 2/3 reasons:

1) consistency: The fluent syntax does not allow something like `Out.Of().Value(3).Pick()`. It compiles only when calling `AndValue()` at least once.
2) 
    * In your case, it is an unexpected behavior, but in other cases, it could be useful, because maybe, someone has accidentally passed only 1 value.
    * Especially when additionally specifying weights (e.g. "please pick form the following values: letter z with weight 37; that's it"), from the library point of view, it looks more like it received wrong input.

To be honest: I don't know what the best solution is (status you, your suggestion, allowing to configure the behavior) and I can't promise you to change the logic.

**Comment by SapiensAnatis** [comment]
That's fair enough. I eventually came up with what I consider to be an acceptable workaround - I created my own implementation of IPick<T> which takes in a single value and always returns that value. Then I just used a factory method to return either that in the 1-element case, or a normal picker in every other case.
