### ISSUE TITLE
PrioritizedElements.Pick(n) returns the same value n times

### ISSUE THREAD

**Issue by SapiensAnatis** [ndsvw/Fluent-Random-Picker#62]
Version: 3.5.0

Reproduction example, slightly modified from the PrioritizedElements example in the docs:

```cs
using FluentRandomPicker;

var items = new Item[]
{
    new Item { Name = "Stone", Rarity = 1 }, // common
    new Item { Name = "Silver helmet", Rarity = 1 }, // uncommon
    new Item { Name = "Gold sword", Rarity = 1 }, // rare
};

IEnumerable<string> pickedItems = Out.Of()
    .PrioritizedElements(items)
    .WithValueSelector(x => x.Name)
    .AndWeightSelector(x => x.Rarity)
    .Pick(10);

foreach (string name in pickedItems)
{
    Console.WriteLine(name);
}
    
class Item {
    public int Rarity { get; set; }
    public string Name { get; set; }
}
```

When I run this the same name is always printed 10 times. I know this is _theoretically_ possible but I am assuming that if it has happened 5+ times in a row for me then there is probably a bug :wink: 

This seems to also affect pickers using percentages instead of weightings.

**Comment by ndsvw** [comment]
Thanks,

I have merged the PR and made a few changes myself.
A bug fix 3.5.1 will be released in a few minutes.
